### ISSUE TITLE
How to add JavaFX libraries to my jar file?

### ISSUE THREAD

**Issue by Ruofan1023** [nus-cs2103-AY2122S1/forum#179]
The jar file I created works well in its created folder. However, after I copied and pasted it onto my Desktop folder, it throws some exceptions as shown below. I suspect it is because I did not add javaFX lib to my jar file. How can I add javafx lib to my jar file? On the website it is not specified how can I achieve this. Thank you for reading my question!

```
nafour@Lenovo:/mnt/c/Users/wangr/Desktop$ java -jar duke.jar
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by damithc** [comment]
@Ruofan1023 What's the size of the JAR file?

**Comment by Ruofan1023** [comment]
8.95 MB

**Comment by damithc** [comment]
> 8.95 MB

The typical size for the iP JAR is around 10-12MB. 
If your image files are several MBs already, it's possible the JavaFX libraries are not in the JAR file. But if your image files are small, the JAR file should be much smaller (e.g., less than 2MB) if the JavaFX libraries have been omitted.

**Comment by damithc** [comment]
This issue from a previous semester might be relevant https://github.com/nus-cs2103-AY2021S2/forum/issues/173

**Comment by simonjulianl** [comment]
Maybe you can try automated jar build using `Gradle` instead and refer to this [solution](https://stackoverflow.com/questions/57452363/building-fatjar-for-javafx-with-gradle-and-intellij-getting-noclassdeffounderro/57452893#57452893) to build a `FatJar`, also seems that you are trying to run it using `WSL`, maybe you can try PowerShell instead to run this

**Comment by Ruofan1023** [comment]
> Maybe you can try automated jar build using `Gradle` instead and refer to this [solution](https://stackoverflow.com/questions/57452363/building-fatjar-for-javafx-with-gradle-and-intellij-getting-noclassdeffounderro/57452893#57452893) to build a `FatJar`, also seems that you are trying to run it using `WSL`, maybe you can try PowerShell instead to run this

Hi Simon long time no see haha! I'm dumb I set default terminal to WSL...It works on PowerShell just fine. I did not make any changes.

**Comment by simonjulianl** [comment]
lmao hi ruofan @Ruofan1023

**Comment by Ruofan1023** [comment]
> This issue from a previous semester might be relevant [nus-cs2103-AY2021S2/forum#173](https://github.com/nus-cs2103-AY2021S2/forum/issues/173)

Encountered the error again when I was testing my jar file on my friend's laptop (macbook, I am using windows). The solution inside the issue mentioned above helped! the [alternative method](https://openjfx.io/openjfx-docs/#gradle) as suggested [here](https://se-education.org/guides/tutorials/gradle.html#creating-jar-files) does not work for me on a different laptop (though it works on my own). 

I used the alternative method because the first time I was attempting the task the suggested one does not work, but I don't know why it works now :/

**Comment by bharathcs** [comment]
> This issue from a previous semester might be relevant [nus-cs2103-AY2021S2/forum#173](https://github.com/nus-cs2103-AY2021S2/forum/issues/173)

Had a similar experience, my JAR was failing on account of missing dependencies on every Linux and windows, but perfectly fine on macOS machines. Fixed it by explicitly calling for all platform releases of JavaFX to be included as per the solution (changed `build.gradle` like [this](73194c0e691e1507342a64dcaf9b44ae4e1fedab)).
