### ISSUE TITLE
Can't run JavaFX Tutorial Step 4

### ISSUE THREAD

**Issue by Smanmos** [nus-cs2103-AY2122S1/forum#234]
I tried running part 4 of the JavaFX tutorial. Even though I copied it exactly, IntelliJ is giving me the following error:
````
javafx.fxml.LoadException: 
/C:/Users/gabri/Documents/CS2103/ip/build/resources/main/view/MainWindow.fxml:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml.FXMLLoader.access$700(FXMLLoader.java:105)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:930)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:980)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:227)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:752)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at duke.Main.start(Main.java:22)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: MainWindow
Caused by: java.lang.ClassNotFoundException: MainWindow

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:928)
	... 17 more
````
I am not sure why there is a `ClassNotFoundException` since this Java class is in my project.

**Comment by Smanmos** [comment]
Found someone with the same issue

https://github.com/nus-cs2103-AY2122S1/forum/issues/131

**Comment by Agentum07** [comment]
Refer to #131 
Edit: Oh you found it seconds before I commented!
