### ISSUE TITLE
Unable to run duke.jar using command

### ISSUE THREAD

**Issue by wengYing227** [nus-cs2103-AY2122S1/forum#249]
I can double-click duke.jar and run it successfully,
but some errors occur when I command ```java -jar duke.jar``` on the terminal.

Error message:
```java
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version
 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by wengYing227** [comment]
@damithc hi Prof, could you help me with this?

**Comment by damithc** [comment]
@wengYing227 which OS?
Can you share these settings?
![image](https://user-images.githubusercontent.com/1673303/133767453-b2166add-499f-4829-8788-c3ae8a4186c7.png)
![image](https://user-images.githubusercontent.com/1673303/133767517-153f24ff-1a6d-4bf0-b0ad-05fa6d7355f0.png)

**Comment by wengYing227** [comment]
@damithc Yes, prof. It's running on Windows System

![image](https://user-images.githubusercontent.com/66865950/133768687-c128b3d9-31cb-45e8-bcec-c7371ac164ec.png)
![image](https://user-images.githubusercontent.com/66865950/133768704-a13e84ac-b107-46c8-ab25-2121432d5510.png)

**Comment by damithc** [comment]
@wengYing227 
Try building the JAR again `gardlew clean shadowJar`
If still doesn't work, run the `java -version` command to check if your terminal is using Java 11

**Comment by damithc** [comment]
Also see https://www.baeldung.com/java-lang-unsupportedclassversion

**Comment by Yukun99** [comment]
I think you probably have Java 8 still installed on your system, and this Windows might be defaulting to that for its pathing. Try uninstalling and checking your windows path variables to see if it's now correctly pointed to JDK 11 for the Java variable. You can see how to change path variables [here](https://www.java.com/en/download/help/path.html). I had the same issue sometimes when I got friends to test my bot and uninstalling or changing path variables fixed it.

**Comment by wengYing227** [comment]
@damithc @Yukun99 Thank you for your help! I've solved this problem so I'm gonna close the issue.
