### ISSUE TITLE
JNI Error Exception in java.lang.UnsupportedClassVersionError (A-TextUiTesting)

### ISSUE THREAD

**Issue by nbvannhi** [nus-cs2103-AY2122S1/forum#43]
Hello everyone! I encountered this error when running ```runtest.bat``` file
```
D:..\iP\text-ui-test>runtest.bat
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bloom has been compiled by a 
more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime 
only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Comparing files ACTUAL.TXT and EXPECTED.TXT
// ACTUAL.TXT and EXPECTED.TXT getting printed
```
I already checked Java Control Panel and it's up to date. ```Bloom``` is my bot name btw :)
Does anyone know how to resolve this?

**Comment by VimuthM** [comment]
I had the same issue on Windows. It's due to compiling and running with clashing java versions. The verified answer in this [StackOverflow post](https://stackoverflow.com/questions/55550802/jni-error-a-class-has-been-compiled-by-a-more-recent-version-of-the-java-runti) worked for me!

**Comment by nbvannhi** [comment]
@VimuthM Thank you for your suggestion but it seems that editing the ```Path``` isn't enough to solve the problem in my case.
After following your recommended post, I found another [post](https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips) and uninstalled Java JRE 8 [manually from the Control Panel](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98), restarted my computer, then it worked :D So, as long as ```java -version``` and ```javac -version``` give the same version, the problem is solved.
