### ISSUE TITLE
runtest.bat no longer work after using package

### ISSUE THREAD

**Issue by SkyBlaise99** [nus-cs2103-AY2122S1/forum#52]
I just shifted my code into new packages and now `runtest.bat` is no longer functioning. I have not modified `runtest.bat`. Is there anything I can do so the text ui testing can run again?
![image](https://user-images.githubusercontent.com/69448615/130313790-cdeb87d1-6e9d-4dab-8f20-c8a97b754e55.png)
```
PS D:\Downloads\IntelliJ IDEA\IdeaProjects\ip\text-ui-test> .\runtest.bat
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <*> at index 17: ..\src\main\java\*.java
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at jdk.compiler/com.sun.tools.javac.main.Option$37.process(Option.java:693)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1088)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:381)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:193)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:229)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
********** BUILD FAILURE **********
```
I suspect that it is because I shifted `Duke.java` into `duke` package, hence i modified `runtest.bat` abit at line 10
`javac  -cp ..\src\main\java\duke -Xlint:none -d ..\bin ..\src\main\java\duke\*.java`
Now I'm getting these errors and idk how to proceed on, some kind souls enlighten me pls tyvm.
```
PS D:\Downloads\IntelliJ IDEA\IdeaProjects\ip\text-ui-test> .\runtest.bat
..\src\main\java\duke\Duke.java:5: error: package duke.exception does not exist
import duke.exception.DukeException;
                     ^
..\src\main\java\duke\Duke.java:6: error: package duke.task does not exist
import duke.task.TaskList;
                ^
..\src\main\java\duke\Duke.java:7: error: package duke.util does not exist
import duke.util.Parser;
                ^
..\src\main\java\duke\Duke.java:8: error: package duke.util does not exist
import duke.util.Storage;
                ^
..\src\main\java\duke\Duke.java:9: error: package duke.util does not exist
import duke.util.Ui;
                ^
..\src\main\java\duke\Duke.java:12: error: cannot find symbol
    private final Storage storage;
                  ^
  symbol:   class Storage
  location: class Duke
..\src\main\java\duke\Duke.java:13: error: cannot find symbol
    private TaskList tasks;
            ^
  symbol:   class TaskList
  location: class Duke
..\src\main\java\duke\Duke.java:14: error: cannot find symbol
    private final Ui ui;
                  ^
  symbol:   class Ui
  location: class Duke
..\src\main\java\duke\Duke.java:22: error: cannot find symbol
        ui = new Ui();
                 ^
  symbol:   class Ui
  location: class Duke
..\src\main\java\duke\Duke.java:23: error: cannot find symbol
        storage = new Storage(filePath);
                      ^
  symbol:   class Storage
  location: class Duke
..\src\main\java\duke\Duke.java:26: error: cannot find symbol
            tasks = new TaskList(storage.load());
                        ^
  symbol:   class TaskList
  location: class Duke
..\src\main\java\duke\Duke.java:27: error: cannot find symbol
        } catch (DukeException | IOException e) {
                 ^
  symbol:   class DukeException
  location: class Duke
..\src\main\java\duke\Duke.java:29: error: cannot find symbol
            tasks = new TaskList();
                        ^
  symbol:   class TaskList
  location: class Duke
..\src\main\java\duke\Duke.java:43: error: cannot find symbol
                String message = Parser.interpretCommand(input).execute(tasks);
                                 ^
  symbol:   variable Parser
  location: class Duke
..\src\main\java\duke\Duke.java:48: error: cannot find symbol
            } catch (DukeException | IOException e) {
                     ^
  symbol:   class DukeException
  location: class Duke
15 errors
********** BUILD FAILURE **********
```

**Comment by damithc** [comment]
@SkyBlaise99 Try using the normal command prompt (not the PowerShell).
As per the following line, you seem to be using the PowerShell.
```
PS D:\Downloads\IntelliJ IDEA\IdeaProjects\ip\text-ui-test> .\runtest.bat
```

**Comment by SkyBlaise99** [comment]
I tried using cmd also but it's the same results. From what I recall i think there is a way to call `javac` on the `.java` files in the subdirectories also right? I believe the issue here is just that only `Duke.java` is being processed and hence it can't find the other files/classes

**Comment by sivayogasubramanian** [comment]
You can try doing something like this https://stackoverflow.com/questions/6623161/javac-option-to-compile-all-java-files-under-a-given-directory-recursively.

I haven't tried it personally because running `runtest.sh` from inside the test dir works.

**Comment by SkyBlaise99** [comment]
Thx for the info. It seems that
`javac com/vistas/util/*.java com/vistas/converter/*.java com.vistas.LineHelper/*.java com/current/mdcontect/*.java`
worked for me for now. Although a bit inefficient but it is working at least. I will look into other methods later.

Another question is that is it safe to delete `-cp ..\src\main\java\duke` part? Is it useful?

**Comment by SkyBlaise99** [comment]
After much googling, I came up with this batch script of my own to handle my case.

Attached below if anyone wish to use it. Remeber to change the path accordingly, my version is the default duke package.
```
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM obtain all .java files in relative path
dir ..\src\main\java\duke /s /b /a-d > sources_raw.txt
(for /f "tokens=1,2 delims= " %%G in (sources_raw.txt) do (
    set "line=%%H"
    setlocal enabledelayedexpansion
    set "line=!line:IDEA\IdeaProjects\ip=..!"
    echo(!line!
    endlocal
)) > sources_modified.txt

REM compile the code into the bin folder
javac -cp ..\src\main\java\duke -Xlint:none -d ..\bin @sources_modified.txt

IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)

REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin duke.Duke < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT
```

**Comment by Chesterwongz** [comment]
I'm trying this, may I know what does
`set "line=!line:IDEA\IdeaProjects\ip=..!"`
Do?

**Comment by SkyBlaise99** [comment]
It removes the first part of the absolute path. Using `dir ..\src\main\java\duke /s /b /a-d > sources_raw.txt`, I'm getting
```
D:\Downloads\IntelliJ IDEA\IdeaProjects\ip\src\main\java\duke\Duke.java
...
```
`set "line=!line:IDEA\IdeaProjects\ip=..!"` is like performing a string replacement and make it all into
```
..\src\main\java\duke\Duke.java
...
```

**Comment by Chesterwongz** [comment]
Thanks! I managed to make it work with your help :D
